/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Vista;

import Control.ClientesControl;
import Control.ProductoControl;
import DAO.ClienteDAO;
import DAO.ProductoDAO;
import javax.swing.JOptionPane;
/**
 *
 * @author alexa
 */
public class Busquedas extends javax.swing.JDialog {
    private String tipoBusqueda;
    private final Ventaform ventaform; // referencia al formulario principal

public Busquedas(Ventaform ventaform, java.awt.Frame parent, boolean modal) {
    super(parent, modal);
    this.ventaform = ventaform; // guarda la referencia
    initComponents();
    setLocationRelativeTo(parent);
}

    // Método público para establecer tipo de búsqueda
    public void setTipoBusqueda(String tipo) {
        this.tipoBusqueda = tipo;
        cargarDatos();
    }

    // Método para cargar datos en la tabla según el tipo
    private void cargarDatos() {
        if ("cliente".equals(tipoBusqueda)) {
        ClientesControl ver= new ClientesControl();
        ver.mostrarclientes(tablabusqueda); // debes tener este método similar al de productos
    } else if ("producto".equals(tipoBusqueda)) {
        ProductoControl ver = new ProductoControl();
        ver.mostrarProductos(tablabusqueda); // el método que tú ya compartiste
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtbusqueda = new javax.swing.JTextField();
        btnbuscar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablabusqueda = new javax.swing.JTable();
        btnaceptar = new javax.swing.JButton();
        btncancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(51, 51, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Buscar", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("BigBlueTerm437 Nerd Font", 0, 12))); // NOI18N

        jLabel1.setFont(new java.awt.Font("BigBlueTerm437 Nerd Font", 0, 14)); // NOI18N
        jLabel1.setText("Buscar");

        txtbusqueda.setFont(new java.awt.Font("BigBlueTerm437 Nerd Font", 0, 14)); // NOI18N

        btnbuscar.setFont(new java.awt.Font("BigBlueTerm437 Nerd Font", 0, 14)); // NOI18N
        btnbuscar.setText("Buscar");

        tablabusqueda.setFont(new java.awt.Font("BigBlueTerm437 Nerd Font", 0, 12)); // NOI18N
        tablabusqueda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tablabusqueda);

        btnaceptar.setFont(new java.awt.Font("BigBlueTerm437 Nerd Font", 0, 14)); // NOI18N
        btnaceptar.setText("Aceptar");
        btnaceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaceptarActionPerformed(evt);
            }
        });

        btncancelar.setFont(new java.awt.Font("BigBlueTerm437 Nerd Font", 0, 14)); // NOI18N
        btncancelar.setText("Cancelar");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(18, 18, 18)
                            .addComponent(txtbusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnbuscar))
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 599, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(btnaceptar)
                        .addGap(217, 217, 217)
                        .addComponent(btncancelar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtbusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnbuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnaceptar)
                    .addComponent(btncancelar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnaceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaceptarActionPerformed
       
         int fila = tablabusqueda.getSelectedRow();
    if (fila == -1) {
        JOptionPane.showMessageDialog(this, "Selecciona una fila.");
        return;
    }

    if ("cliente".equals(tipoBusqueda)) {
    try {
        // Obtener valores de la tabla
        String dni = tablabusqueda.getValueAt(fila, 3).toString();
        String nombre = tablabusqueda.getValueAt(fila, 1).toString();
        
        // Validación básica
        if(dni == null || dni.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "El DNI no puede estar vacío", 
                                        "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        // Crear cliente solo con nombre y DNI
        ClienteDAO cliente = new ClienteDAO(nombre, dni);
        ventaform.setCliente(cliente);
        
    } catch (IllegalArgumentException e) {
        JOptionPane.showMessageDialog(this, e.getMessage(), 
                                     "Error", JOptionPane.ERROR_MESSAGE);
        return;
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error inesperado: " + e.getMessage(), 
                                     "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    } else if ("producto".equals(tipoBusqueda)) {
        String nombre = tablabusqueda.getValueAt(fila, 1).toString();
        int cantidad = Integer.parseInt(tablabusqueda.getValueAt(fila, 4).toString());
        double precio = Double.parseDouble(tablabusqueda.getValueAt(fila, 3).toString());
        ProductoDAO producto = new ProductoDAO(nombre, cantidad, precio);
        ventaform.agregarProducto(producto); // usa el método público
    }

    this.dispose(); //
        
    }//GEN-LAST:event_btnaceptarActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnaceptar;
    private javax.swing.JButton btnbuscar;
    private javax.swing.JButton btncancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tablabusqueda;
    private javax.swing.JTextField txtbusqueda;
    // End of variables declaration//GEN-END:variables
}
